demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('myapp/', include('myapp.urls')),
    path('admin/', admin.site.urls),
]


# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG == True:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/myapp/', permanent=True)),
]



#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

myapp/urls.py
from django.urls import path
from . import views

urlpatterns =[
	path('',views.index, name='index'),
]

urlpatterns += [
    path('api/get_produto_info', views.get_produto_info, name='get_produto_info'),
    path('api/get_representada_info', views.get_representada_info, name='get_representada_info'),
]

urlpatterns += [
    path('representadas/', views.RepresentadaListView.as_view(), name='representadas'),
    path('representada/<int:pk>', views.RepresentadaDetailView.as_view(), name='representada-detail'),
    path('representada/create/', views.RepresentadaCreate.as_view(), name='representada-create'),
    path('representada/<int:pk>/update/', views.RepresentadaUpdate.as_view(), name='representada-update'),
    path('representada/<int:pk>/delete/', views.RepresentadaDelete.as_view(), name='representada-delete'),
]

urlpatterns += [
    path('pedidos/', views.PedidoListView.as_view(), name='pedidos'),
    path('pedido/<int:pk>', views.PedidoDetailView.as_view(), name='pedido-detail'),
    path('pedido/create/', views.PedidoCreate.as_view(), name='pedido-create'),
    path('pedido/<int:pk>/update/', views.PedidoUpdate.as_view(), name='pedido-update'),
    path('pedido/<int:pk>/delete/', views.PedidoDelete.as_view(), name='pedido-delete'),
    path('pedido/<int:pk>/pdf/', views.pedido_pdf_view, name='pedido-pdf'),
]


urlpatterns += [
    path('produtos/', views.ProdutoListView.as_view(), name='produtos'),
    path('produto/<int:pk>', views.ProdutoDetailView.as_view(), name='produto-detail'),
    path('produto/create/', views.ProdutoCreate.as_view(), name='produto-create'),
    path('produto/<int:pk>/update/', views.ProdutoUpdate.as_view(), name='produto-update'),
    path('produto/<int:pk>/delete/', views.ProdutoDelete.as_view(), name='produto-delete'),
]

urlpatterns += [
    path('assistencias/', views.AssistenciaListView.as_view(), name='assistencias'),
    path('assistencia/<int:pk>', views.AssistenciaDetailView.as_view(), name='assistencia-detail'),
    path('assistencia/create/', views.AssistenciaCreate.as_view(), name='assistencia-create'),
    path('assistencia/<int:pk>/update/', views.AssistenciaUpdate.as_view(), name='assistencia-update'),
    path('assistencia/<int:pk>/delete/', views.AssistenciaDelete.as_view(), name='assistencia-delete'),
    path('assistencia/<int:pk>/pdf/', views.assistencia_pdf_view, name='assistencia-pdf'),
]

urlpatterns += [
    path('clientes/', views.ClienteListView.as_view(), name='clientes'),
    path('cliente/<int:pk>', views.ClienteDetailView.as_view(), name='cliente-detail'),
    path('cliente/create/', views.ClienteCreate.as_view(), name='cliente-create'),
    path('cliente/<int:pk>/update/', views.ClienteUpdate.as_view(), name='cliente-update'),
    path('cliente/<int:pk>/delete/', views.ClienteDelete.as_view(), name='cliente-delete'),
]

urlpatterns += [
    path('transportadoras/', views.TransportadoraListView.as_view(), name='transportadoras'),
    path('transportadora/<int:pk>', views.TransportadoraDetailView.as_view(), name='transportadora-detail'),
    path('transportadora/create/', views.TransportadoraCreate.as_view(), name='transportadora-create'),
    path('transportadora/<int:pk>/update/', views.TransportadoraUpdate.as_view(), name='transportadora-update'),
    path('transportadora/<int:pk>/delete/', views.TransportadoraDelete.as_view(), name='transportadora-delete'),
]

urlpatterns += [
    path('vendedores/', views.VendedorListView.as_view(), name='vendedores'),
    path('vendedor/<int:pk>', views.VendedorDetailView.as_view(), name='vendedor-detail'),
    path('vendedor/create/', views.VendedorCreate.as_view(), name='vendedor-create'),
    path('vendedor/<int:pk>/update/', views.VendedorUpdate.as_view(), name='vendedor-update'),
    path('vendedor/<int:pk>/delete/', views.VendedorDelete.as_view(), name='vendedor-delete'),
]

urlpatterns += [
    path('acabamentos/', views.AcabamentoListView.as_view(), name='acabamentos'),
    path('acabamento/<int:pk>', views.AcabamentoDetailView.as_view(), name='acabamento-detail'),
    path('acabamento/create/', views.AcabamentoCreate.as_view(), name='acabamento-create'),
    path('acabamento/<int:pk>/update/', views.AcabamentoUpdate.as_view(), name='acabamento-update'),
    path('acabamento/<int:pk>/delete/', views.AcabamentoDelete.as_view(), name='acabamento-delete'),
]

urlpatterns += [
    path('tecidos/', views.TecidoListView.as_view(), name='tecidos'),
    path('tecido/<int:pk>', views.TecidoDetailView.as_view(), name='tecido-detail'),
    path('tecido/create/', views.TecidoCreate.as_view(), name='tecido-create'),
    path('tecido/<int:pk>/update/', views.TecidoUpdate.as_view(), name='tecido-update'),
    path('tecido/<int:pk>/delete/', views.TecidoDelete.as_view(), name='tecido-delete'),
]

urlpatterns += [
    path('formasPagamento/', views.FormaPagamentoListView.as_view(), name='formasPagamento'),
    path('formaPagamento/<int:pk>', views.FormaPagamentoDetailView.as_view(), name='formaPagamento-detail'),
    path('formaPagamento/create/', views.FormaPagamentoCreate.as_view(), name='formaPagamento-create'),
    path('formaPagamento/<int:pk>/update/', views.FormaPagamentoUpdate.as_view(), name='formaPagamento-update'),
    path('formaPagamento/<int:pk>/delete/', views.FormaPagamentoDelete.as_view(), name='formaPagamento-delete'),
]

urlpatterns += [
    path('relatorios/', views.Relatorios.as_view(), name='relatorios'),
    path('relatorio/clientes/', views.relatorio_clientes_view, name='relatorio-clientes'),
    path('relatorio/representadas/', views.relatorio_representadas_view, name='relatorio-representadas'),
    path('relatorio/produtos-por-repr/', views.relatorio_produtos_por_repr_view, name='relatorio-produtos-por-repr'),
    path('relatorio/produtos-por-repr/<int:pk>', views.relatorio_produtos_por_repr_view, name='relatorio-produtos-por-repr-pk'),
    path('relatorio/clientes-por-prod/', views.relatorio_produtos_por_cliente, name='relatorio-clientes-por-prod'),
    path('relatorio/clientes-por-prod/<int:pk>', views.relatorio_produtos_por_cliente, name='relatorio-clientes-por-prod-pk'),
    path('relatorio/comissao-por-repr/', views.relatorio_comissao_por_representada, name='relatorio-comissao-por-repr'),
    path('relatorio/comissao-por-repr/<int:pk>', views.relatorio_comissao_por_representada, name='relatorio-comissao-por-repr-pk'),
    
]

myapp/models.py
from django.db import models
from django.urls import reverse  # To generate URLS by reversing URL patterns
import uuid  # Required for unique book instances
from datetime import date
import datetime
from .soft_delete import *
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    avatar = models.ImageField() # or whatever

    def __str__(self):
        return self.user.email

class Representada(SoftDeletionModel):
    nome = models.CharField(max_length=255,
                            help_text="Nome da representada")
    contato = models.CharField(max_length=255, blank=True)    
    cnpj = models.CharField(max_length=255)
    inscEstadual = models.CharField(max_length=255)
    inscMunicipal = models.CharField(max_length=255, blank=True)
    estado = models.CharField(max_length=255)
    cidade = models.CharField(max_length=255)
    cep = models.CharField(max_length=255)
    endereco = models.CharField(max_length=255)
    bairro = models.CharField(max_length=255)
    telefone = models.CharField(max_length=255)
    celular = models.CharField(max_length=255, blank=True)
    email = models.EmailField(max_length=255)
    linha = models.CharField(max_length=255, blank=True)
    comissao = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    ipi = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    lastUpdate = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['nome']

    def get_absolute_url(self):
        return reverse('representada-detail', args=[str(self.id)])

    def __str__(self):
        return self.nome

    def get_text(self):
        fields_dict = [ ('Nome: ', self.nome),
                        ('Contato: ',self.contato),
                        ('CNPJ: ', self.cnpj),
                        ('Cidade: ', self.cidade)]
        return fields_dict

    def get_edit_url(self):
        return reverse('representada-update', args=[str(self.id)])

    def get_delete_url(self):
        return reverse('representada-delete', args=[str(self.id)])



class Produto(SoftDeletionModel):
    nome = models.CharField(max_length=255,
                            help_text="Nome do produto")
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    referencia = models.CharField(max_length=255)
    representada = models.ForeignKey('Representada', on_delete=models.SET_NULL, null=True)
    observacoes = models.TextField(max_length=600, blank=True, null=True)
    lastUpdate = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['nome']

    def get_absolute_url(self):
        return reverse('produto-detail', args=[str(self.id)])

    def __str__(self):
        return self.nome

    def get_text(self):
        fields_dict = [ ('Código: ', self.id),
                        ('Nome: ', self.nome),
                        ('Referência: ',self.referencia),
                        ('Valor: ', self.valor),
                        ('Representada: ', self.representada)]
        return fields_dict

    def get_edit_url(self):
        return reverse('produto-update', args=[str(self.id)])

    def get_delete_url(self):
        return reverse('produto-delete', args=[str(self.id)])


class Status(SoftDeletionModel):
    status = models.CharField(max_length=255)

    def __str__(self):
        return self.status


class TipoFrete(SoftDeletionModel):
    tipoFrete = models.CharField(max_length=255)

    def __str__(self):
        return self.tipoFrete

class TipoCobranca(SoftDeletionModel):
    tipoCobranca = models.CharField(max_length=255)

    def __str__(self):
        return self.tipoCobranca


class Pedido(SoftDeletionModel):
    data = models.DateField()
    ordemCompra = models.CharField(max_length=255)
    status = models.ForeignKey('Status', on_delete=models.SET_NULL, null=True, default=1)
    cliente = models.ForeignKey('Cliente', on_delete=models.SET_NULL, null=True)
    representada = models.ForeignKey('Representada', on_delete=models.SET_NULL, null=True)
    vendedor = models.ForeignKey('Vendedor', on_delete=models.SET_NULL, null=True)
    transportadora = models.ForeignKey('Transportadora', on_delete=models.SET_NULL, null=True)
    tipoFrete = models.ForeignKey('TipoFrete', on_delete=models.SET_NULL, null=True)
    formaPagamento = models.ForeignKey('FormaPagamento', on_delete=models.SET_NULL, null=True)
    tipoCobranca = models.ForeignKey('TipoCobranca', on_delete=models.SET_NULL, null=True)

    lastUpdate = models.DateTimeField(auto_now=True)

    #Itens do Pedido
    
    
    #Valor do Pedido
    valorBruto = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    desconto1 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    desconto2 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    desconto3 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    desconto4 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    desconto5 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    ipi = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    valorIpi = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    valorTotal = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    porcentagemComissao = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    valorComissao = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    observacoes = models.TextField(max_length=600, blank=True)


    def get_absolute_url(self):
        return reverse('pedido-detail', args=[str(self.id)])

    def __str__(self):        
        if self.id:
            return str(self.id)
        return self.ordemCompra

    def get_text(self):
        fields_dict = [ ('N° Pedido: ',self.id),
                        ('Cliente: ', self.cliente),
                        ('Representada: ', self.representada)]
        return fields_dict

    def get_edit_url(self):
        return reverse('pedido-update', args=[str(self.id)])

    def get_delete_url(self):
        return reverse('pedido-delete', args=[str(self.id)])

    def get_valor_descontos_aplicado(self):
        valor_bruto = self.valorBruto
        if self.desconto1 > 0:
            valor_bruto =  valor_bruto * ((100 - self.desconto1)/100)
        if self.desconto2 > 0:
            valor_bruto =  valor_bruto * ((100 - self.desconto2)/100)
        if self.desconto3 > 0:
            valor_bruto =  valor_bruto * ((100 - self.desconto3)/100)
        if self.desconto4 > 0:
            valor_bruto =  valor_bruto * ((100 - self.desconto4)/100)
        if self.desconto5 > 0:
            valor_bruto =  valor_bruto * ((100 - self.desconto5)/100)

        return round(valor_bruto, 2)

class ItemPedido(SoftDeletionModel):
    pedido = models.ForeignKey('Pedido', on_delete=models.SET_NULL, null=True)
    produto = models.ForeignKey('Produto', on_delete=models.SET_NULL, null=True)
    referencia = models.CharField(max_length=200)
    acabamento = models.ForeignKey('Acabamento', on_delete=models.SET_NULL, null=True)
    tecido = models.ForeignKey('Tecido', on_delete=models.SET_NULL, null=True)
    quantidade = models.IntegerField(default=0)
    valorUnitario = models.DecimalField(max_digits=10, decimal_places=2)
    valorParcial = models.DecimalField(max_digits=10, decimal_places=2)
    lastUpdate = models.DateTimeField(auto_now=True)

    def get_valorParcial(self):
        return self.produto.valor * self.quantidade

    def __str__(self):
        if self.produto and self.pedido:
            return self.produto.nome +" "+ self.pedido.ordemCompra +" "+self.produto.referencia
        return self.referencia


class Cliente(SoftDeletionModel):
    razaoSocial = models.CharField(max_length=500)
    nomeFantasia = models.CharField(max_length=500)
    regiao = models.CharField(max_length=500, blank=True)
    diretor = models.CharField(max_length=500)
    comprador = models.CharField(max_length=500)
    financeiro = models.CharField(max_length=500, blank=True)
    regApuracao = models.CharField(max_length=500, null=True, help_text="Regime de apuração", blank=True)
    telefone = models.CharField(max_length=500)
    celular = models.CharField(max_length=500, blank=True)
    email = models.EmailField(max_length=500)
    observacoes = models.CharField(max_length=500, blank=True)

    # Dados de Faturamento
    fat_inscEstadual = models.CharField(max_length=500, blank=True)
    fat_estado = models.CharField(max_length=500, blank=True)
    fat_cidade = models.CharField(max_length=500, blank=True)
    fat_cep = models.CharField(max_length=500, blank=True)
    fat_endereco = models.CharField(max_length=500, blank=True)
    fat_bairro = models.CharField(max_length=500, blank=True)
    fat_cnpj = models.CharField(max_length=500, blank=True)

    # Dados de Cobrança
    cob_inscEstadual = models.CharField(max_length=500, blank=True)
    cob_estado = models.CharField(max_length=500, blank=True)
    cob_cidade = models.CharField(max_length=500, blank=True)
    cob_cep = models.CharField(max_length=500, blank=True)
    cob_endereco = models.CharField(max_length=500, blank=True)
    cob_bairro = models.CharField(max_length=500, blank=True)
    cob_cnpj = models.CharField(max_length=500, blank=True)

    # Dados de Entrega
    entr_inscEstadual = models.CharField(max_length=500, blank=True)
    entr_estado = models.CharField(max_length=500, blank=True)
    entr_cidade = models.CharField(max_length=500, blank=True)
    entr_cep = models.CharField(max_length=500, blank=True)
    entr_endereco = models.CharField(max_length=500, blank=True)
    entr_bairro = models.CharField(max_length=500, blank=True)
    entr_cnpj = models.CharField(max_length=500, blank=True)


    lastUpdate = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        ordering = ['razaoSocial']

    def get_absolute_url(self):

myapp/templates/myapp/acabamento_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Acabamento: {{ acabamento }} </h1>

{% endblock %}

myapp/templates/myapp/assistencia_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div class="obj-list-container">
  <h1>Deletar Assistencia</h1>

  <p>Você tem certeza que quer deletar o cadastro de número {{ assistencia.id }} ?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" action="" value="Sim" />
    <a href="{% url 'assistencias' %}"><input class="btn btn-secondary" type="button" value="Cancelar" /></a>
  </form>
</div>

{% endblock %}

myapp/templates/myapp/cliente_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Cliente: {{ cliente }} </h1>

{% endblock %}

myapp/templates/myapp/formapagamento_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div class="obj-list-container">
  <h1>Deletar Forma de Pagamento</h1>

  <p>Você tem certeza que quer deletar o cadastro de número {{ formapagamento.id }} ?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" action="" value="Sim" />
    <a href="{% url 'formasPagamento' %}"><input class="btn btn-secondary" type="button" value="Cancelar" /></a>
  </form>
</div>
{% endblock %}

myapp/templates/myapp/pedido_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div class="obj-list-container">
  <h1>Deletar Pedido</h1>

  <p>Você tem certeza que quer deletar o cadastro de número {{ pedido.id }} ?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" action="" value="Sim" />
    <a href="{% url 'pedidos' %}"><input class="btn btn-secondary" type="button" value="Cancelar" /></a>
  </form>
</div>
{% endblock %}

myapp/templates/myapp/pedido_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Pedido: {{ pedido }} </h1>

{% endblock %}

myapp/templates/myapp/produto_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Produto: {{ produto }} </h1>

{% endblock %}

myapp/templates/myapp/relatorio_comissao_por_representada.html
{% load static %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Lista de Comissão por Representada</title>
        <style type="text/css">
            @page {
                size: A4;
                margin: 1cm;
            }
            
            .items-table, td, th {  
                border-bottom: 1px solid #ddd;
                border-top: 1px solid #ddd;
                text-align: left;
                padding: 5px;
            }
            .items-table {
                border-collapse: collapse;
                width: 100%;
            }
            
            /* .td{
                word-break: none;
            } */
            .list-group p {
                font-size: 1em;
            }

            .table1, .table-cliente, .table-valores, .table-resumo{
                width: 100%;
                max-width: 100%;
                margin-bottom: 5px;
                background-color: #fff;
            }
            .table1, .table-cliente, .table-valores{
                border: none;
            }
            
            .table1 td, .table-cliente td, .table-valores td, .table-resumo td {
                border: none;
                vertical-align: top;
            }
            .table-valores{
                margin-top:20px;
            }
            .inner-table{
                width: 100%;
                max-width: 100%;
                background-color: #fff;
                border: none;
                text-align: start;
            }

            .inner-table td{
                padding: 0px;
            }
            
            .inner-table .field-td{
                width: 35%; 
                font-weight: bold;
                text-align: start;
                margin-left: 10px;
            }

            .inner-table .value-td{
                width: 65%; 
                text-align: start;
            }
            
            .company-info-table, .order-info-table{
                text-align: start;
            }
            .cliente-info, .representada-info, .valores-info{
                text-align: start;
                padding: 0px;
            }
            .cliente-info h2, .representada-info h2{
                margin: 10px 0px 0px 0px;
                padding: 0px;

            }
            

        </style>
    </head>
    <body>
        <div class="container">
            <div class="card">
                <!-- <table class="table1">
                    <td style="width: 120px"><img src="/home/miguelguida/www/static/dist/img/logo.jpeg" height="85px"/></td>
                   
                    <td style="width: 40%">
                        <div class="company-info-table">
                            <table class="inner-table">
                                <tr><td class="field-td">Telefone: </td><td class="value-td"> (14) 3422-1610</td></tr>
                                <tr><td class="field-td">Celular: </td><td class="value-td"> (14) 98129-8551 e (14) 98129-8610</td></tr>
                                <tr><td class="field-td">E-mail: </td><td class="value-td"> contato@ngrepresentacoes.com.br</td></tr>
                                <tr><td class="field-td">Endereço: </td><td class="value-td"> Rua André Martins Parra, 250 - C41</td></tr>
                                <tr><td class="field-td">Bairro: </td><td class="value-td"> Jardim Colibri</td></tr>
                                <tr><td class="field-td">Cidade: </td><td class="value-td"> Marília-SP</td></tr>
                            </table>
                            
                        </div>
                        
                    </td>
                    <td style="width: 50%">
                        
                        <div class="order-info-table">
                            <table class="inner-table">
                                <tr><td class="field-td">Nr. Pedido: </td><td class="value-td"> {{ pedido.id }}</td></tr>
                                <tr><td class="field-td">Ordem de Compra: </td><td class="value-td"> {{ pedido.ordemCompra }}</td></tr>
                                <tr><td class="field-td">Vendedor: </td><td class="value-td"> {{ pedido.vendedor.nome }}</td></tr>
                                <tr><td class="field-td">Data: </td><td class="value-td"> {{ pedido.data }}</td></tr>
                            </table>
                            
                        </div>
                        
                    </td>
                </table> -->
                <h1>Lista de Comissão por Representada</h1>

                <hr/>

                {% for r, p_list in pedidos.items %}
                <h3>Representada: {{ r.nome }}</h3>
                <table class="items-table">
                    <thead>
                        <tr>
                            <th>Número Pedido</th>
                            <th>Cliente</th>
                            <th>Valor Pedido</th>
                            <th>Valor Comissão</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for p in p_list %}
                        <tr>
                            <td>{{ p.id }}</td>
                            <td>{{ p.cliente }}</td>
                            <td>{{ p.valorTotal }}</td>
                            <td>{{ p.valorComissao }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                </table>
                <br/>
                <br/>
                <br/>

                {% endfor %}

                
                
            </div>
        </div>

    </body>
</html>

myapp/templates/myapp/transportadora_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div class="obj-list-container">
  <h1>Deletar Transportadora</h1>

  <p>Você tem certeza que quer deletar o cadastro de número {{ transportadora.id }} ?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" action="" value="Sim" />
    <a href="{% url 'transportadoras' %}"><input class="btn btn-secondary" type="button" value="Cancelar" /></a>
  </form>
</div>
{% endblock %}

myapp/templates/myapp/transportadora_form.html
{% extends "base_generic.html" %}
{% load widget_tweaks %}
{% block content %}
    
    <div class="form-container">
        <h1 class="mb-5">{{ createUpdate }} Transportadora</h1>

        <form action="" method="post">
            {% csrf_token %}
           
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label>Nome</label>
                    {{ form.nome|add_class:'form-control' }}
                </div>
                <div class="form-group col-md-6">
                    <label>Contato</label>
                    {{ form.contato|add_class:'form-control' }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label>CNPJ</label>
                    {{ form.cnpj|add_class:'form-control' }}
                </div>
                <div class="form-group col-md-3">
                    <label>Inscrição Estadual</label>
                    {{ form.inscEstadual|add_class:'form-control' }}
                </div>
                <div class="form-group col-md-2">
                    <label>Telefone</label>
                    {{ form.telefone|add_class:'form-control' }}
                </div>
                <div class="form-group col-md-2">
                    <label>Celular</label>
                    {{ form.celular|add_class:'form-control' }}
                </div>
                <div class="form-group col-md-3">
                    <label>Email</label>
                    {{ form.email|add_class:'form-control' }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label>CEP</label>
                    {{ form.cep|add_class:'form-control' }}
                </div>
                <div class="form-group col-md-3">
                    <label>Cidade</label>
                    {{ form.cidade|add_class:'form-control' }}
                </div>
                <div class="form-group col-md-1">
                    <label>Estado</label>
                    {{ form.estado|add_class:'form-control' }}
                </div>
                <div class="form-group col-md-3">
                    <label>Bairro</label>
                    {{ form.bairro|add_class:'form-control' }}
                </div>
                <div class="form-group col-md-3">
                    <label>Endereco</label>
                    {{ form.endereco|add_class:'form-control' }}
                </div>
                
            </div>
            <div class="form-row">
                
                <div class="form-group col-md-6">
                    <label>Observações</label>
                    {{ form.observacoes|add_class:'form-control' }}
                </div>
            </div>
            

            <!-- <div class="input-group">
                <label>observacoes</label>
                <div class="input-group-append">
                    <div class="input-group-text"> <span class="fas fa-user"></span> </div>
                </div>
                
                {{ form.observacoes|add_class:'form-control' }}
            </div>   -->
          
            
            <input class="btn btn-primary submit-btn" type="submit" value="Salvar" />
            <a href="{% url 'transportadoras' %}"><input class="btn btn-secondary submit-btn" type="button" value="Cancelar" /></a>
            
        </form>
    </div>
<script>
    $("#id_cnpj").mask("99.999.999/9999-99");
    $("#id_cep").mask("99999-999");
    $("#id_telefone").mask("(99) 9999-9999");
    $("#id_celular").mask("(99) 99999-9999");
    var cep = document.getElementById("id_cep")
    cep.onblur = function(){
        console.log("poaspoaspoaspoaspoaspo")
        var url = "https://viacep.com.br/ws/"+cep.value+"/json/";
                
        // Faz a pesquisa do CEP, tratando o retorno com try/catch para que
        // caso ocorra algum erro (o cep pode não existir, por exemplo) a
        // usabilidade não seja afetada, assim o usuário pode continuar//
        // preenchendo os campos normalmente
        fetch(url, {
            method: 'get'
        })
        .then(response => response.json())
        .then(data => {
            console.log(data)
            document.getElementById("id_estado").value = data.uf
            document.getElementById("id_endereco").value = data.logradouro
            document.getElementById("id_cidade").value = data.localidade
            document.getElementById("id_bairro").value = data.bairro

        }).catch(function(err) {
            // Error :(
        });
    };
    


</script>
{% endblock %}

myapp/templates/myapp/vendedor_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Vendedor: {{ vendedor }} </h1>

{% endblock %}